apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    app: dockerpoc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
      protocol: TCP
      name: app
  selector:
    app: dockerpoc
