apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
  labels:
    app: user-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 32672
      nodePort: 32672
      protocol: TCP
      name: user-service-appport
  selector:
    app: user-app
