apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  selector:
    matchLabels:
      app: user-service-app
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
        - name: user-service-container
          image: shahpriti919/user-service
          ports:
            - containerPort: 8080